# Generated by Django 2.2 on 2019-05-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
