# Generated by Django 2.2.1 on 2019-05-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190502_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='preco',
            field=models.TextField(max_length=20),
        ),
    ]
